import { FiArrowDownRight, FiArrowUpRight, FiBarChart2, FiBriefcase, FiDollarSign, FiTarget, FiUsers } from "react-icons/fi";
import { departmentData } from "../data/hiringData";

export default function Analytics() {
  const jobs = [{ name: "Frontend Engineer", count: 42, rate: 100 }, { name: "Senior Product Designer", count: 31, rate: 74 }, { name: "Data Analyst", count: 28, rate: 67 }, { name: "Growth Marketing Manager", count: 19, rate: 45 }];
  return <div><div className="page-title-row"><div><p className="eyebrow">Hiring intelligence</p><h1>Recruitment analytics</h1><p>Turn your talent data into faster, better hiring decisions.</p></div><select className="period-select"><option>Last 90 days</option><option>This year</option></select></div><div className="analytics-stats">{[
    [FiDollarSign, "Avg. salary expectation", "₹21.4 LPA", "+6.2%", true], [FiBriefcase, "Most applied role", "Frontend Engineer", "42 applicants", true], [FiTarget, "Hiring conversion", "17.7%", "+2.8%", true], [FiUsers, "Avg. time to hire", "18 days", "-3.1 days", false]
  ].map(([Icon, label, value, delta, up]) => <article className="dashboard-card analytics-stat" key={label}><span><Icon /></span><p>{label}</p><strong>{value}</strong><small className={up ? "up" : "down"}>{up ? <FiArrowUpRight /> : <FiArrowDownRight />}{delta} <em>vs last period</em></small></article>)}</div><div className="analytics-grid"><section className="dashboard-card hiring-trend"><div className="card-heading"><div><h2>Application trend</h2><p>Applicants received over the last 12 weeks</p></div><div className="chart-key"><span><i /> Applications</span><span><i /> Interviews</span></div></div><div className="line-chart"><svg viewBox="0 0 800 250" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7357e8" stopOpacity=".28"/><stop offset="1" stopColor="#7357e8" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 220 C80 210,100 145,180 165 S290 70,370 110 S480 80,540 100 S650 30,800 48 L800 250 L0 250Z"/><path className="line primary" d="M0 220 C80 210,100 145,180 165 S290 70,370 110 S480 80,540 100 S650 30,800 48"/><path className="line secondary" d="M0 235 C90 225,120 205,190 213 S300 155,375 180 S490 145,550 165 S665 108,800 118"/></svg><div className="chart-labels"><span>Apr 1</span><span>Apr 15</span><span>May 1</span><span>May 15</span><span>Jun 1</span><span>Jun 15</span></div></div></section><section className="dashboard-card department-breakdown"><div className="card-heading"><div><h2>By department</h2><p>Share of all applications</p></div><FiBarChart2 /></div>{departmentData.map((item) => <div className="dept-row" key={item.label}><span><i style={{background: item.color}} />{item.label}</span><div><em style={{width: `${item.value * 2}%`, background: item.color}} /></div><strong>{item.value}</strong></div>)}</section><section className="dashboard-card popular-roles"><div className="card-heading"><div><h2>Most applied jobs</h2><p>Roles drawing the most candidate interest</p></div></div>{jobs.map((job, i) => <div className="role-rank" key={job.name}><strong>0{i+1}</strong><div><span>{job.name}<b>{job.count}</b></span><i><em style={{width: `${job.rate}%`}} /></i></div></div>)}</section><section className="dashboard-card funnel-card"><div className="card-heading"><div><h2>Hiring funnel</h2><p>Conversion across stages</p></div></div>{[["Applied", 124, 100], ["Screened", 82, 82], ["Interviewed", 46, 62], ["Shortlisted", 28, 45], ["Hired", 22, 34]].map(([label, value, width]) => <div className="funnel-row" key={label}><span>{label}</span><i style={{width: `${width}%`}}><b>{value}</b></i></div>)}</section></div></div>;
}
