import { useMemo, useState } from "react";
import { FiCheck, FiChevronDown, FiClock, FiMail, FiMessageCircle, FiMoreHorizontal, FiPaperclip, FiSearch, FiSend } from "react-icons/fi";
import { useHiring } from "../App";

const templates = ["Thanks for applying! We’ll review your profile and share next steps soon.", "A quick reminder about your interview tomorrow. Looking forward to speaking with you!", "We’re delighted to move forward. Can we schedule time to discuss the offer?"];
const seed = {
  "APP-2026-0041": [{ from: "candidate", text: "Hi Neha, thank you for scheduling the interview. I’m looking forward to meeting the engineering team!", time: "10:14 AM" }, { from: "hr", text: "Lovely to hear, Priya. I’ve shared the calendar invite and a short overview of what to expect.", time: "10:18 AM" }],
  "APP-2026-0040": [{ from: "candidate", text: "Hello! I’ve added the case study password to my application notes.", time: "Yesterday" }]
};
export default function Messages() {
  const { applicants } = useHiring(); const [selected, setSelected] = useState(applicants[0]?.id); const [search, setSearch] = useState(""); const [messages, setMessages] = useState(seed); const [draft, setDraft] = useState(""); const person = applicants.find(a => a.id === selected);
  const filtered = useMemo(() => applicants.filter((p) => p.name.toLowerCase().includes(search.toLowerCase())).slice(0, 5), [applicants, search]);
  const send = () => { if (!draft.trim()) return; setMessages((prev) => ({ ...prev, [selected]: [...(prev[selected] || []), { from: "hr", text: draft, time: "Now" }] })); setDraft(""); };
  return <div><div className="page-title-row"><div><p className="eyebrow">Candidate communication</p><h1>Messages</h1><p>Keep every candidate conversation warm, timely, and in one place.</p></div></div><div className="chat-shell dashboard-card"><aside className="chat-list"><div className="chat-list-head"><h2>Conversations</h2><button><FiMoreHorizontal /></button></div><div className="chat-search"><FiSearch /><input placeholder="Search conversations" value={search} onChange={(e) => setSearch(e.target.value)} /></div>{filtered.map((item, index) => <button className={`chat-person ${selected === item.id ? "active" : ""}`} onClick={() => setSelected(item.id)} key={item.id}><span className="avatar">{item.avatar}</span><div><span><strong>{item.name}</strong><small>{index === 0 ? "10:18 AM" : "Yesterday"}</small></span><p>{messages[item.id]?.at(-1)?.text || "Start a conversation"}</p></div>{index === 1 && <i />}</button>)}</aside><section className="chat-main"><header className="chat-header"><div><span className="avatar">{person?.avatar}</span><div><strong>{person?.name}</strong><small><i /> Active now · {person?.role}</small></div></div><button><FiMail /></button><button><FiMoreHorizontal /></button></header><div className="message-history"><div className="date-divider"><span>Today</span></div>{(messages[selected] || []).map((message, index) => <div className={`message ${message.from}`} key={index}><div>{message.text}</div><small>{message.time} {message.from === "hr" && <FiCheck />}</small></div>)}</div><div className="quick-templates"><span>Quick replies</span>{templates.map((template, i) => <button key={template} onClick={() => setDraft(template)}>{i === 0 ? "Application update" : i === 1 ? "Interview reminder" : "Offer discussion"}</button>)}</div><div className="message-compose"><button><FiPaperclip /></button><textarea rows="1" placeholder={`Message ${person?.name.split(" ")[0]}…`} value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} /><button className="send-button" onClick={send}><FiSend /></button></div></section><aside className="chat-details"><span className="avatar profile-avatar">{person?.avatar}</span><h3>{person?.name}</h3><p>{person?.role}</p><span className="status-pill interview-scheduled">{person?.status}</span><div><small>Email</small><a href={`mailto:${person?.email}`}>{person?.email}</a><small>Phone</small><strong>{person?.phone}</strong><small>Applied</small><strong>{person?.applied}</strong></div><button className="button button-ghost"><FiClock /> View candidate timeline</button></aside></div></div>;
}
